{
 "title": "Energy import",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Imported Current Ampere",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "homeassistant_sensor_current_a{entity=~\"sensor.p1.*\"}\n",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Max Imported Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "max_over_time(homeassistant_sensor_current_a{entity=~\"sensor.p1.*\"} [1d])\n",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Imported power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.p1_meter_effekt\"} /1000\n",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Max Imported power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "max_over_time(homeassistant_sensor_power_w{entity=\"sensor.p1_meter_effekt\"} /1000 [1d])",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Imported energy kWh/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(homeassistant_sensor_energy_kwh{entity=\"sensor.p1_meter_total_elimport\"} [1h])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Imported energy kWh/d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(homeassistant_sensor_energy_kwh{entity=\"sensor.p1_meter_total_elimport\"} [1d])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}