alias: Set morning temperature
description: ""
triggers:
  - trigger: time
    at: "03:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
conditions: []
actions:
  - action: climate.set_temperature
    target:
      entity_id: climate.golvvarmen
    data:
      temperature: "24"
      hvac_mode: heat
mode: single
